services:

  # ===============================
  # PostgreSQL
  # ===============================
  postgres:
    image: postgres:16
    container_name: srni_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: srni_db
      POSTGRES_USER: srni_user
      POSTGRES_PASSWORD: srni_pass
    volumes:
      - srni_pgdata:/var/lib/postgresql/data
    networks:
      - srni_net

  # ===============================
  # Django Backend (interno)
  # ===============================
  backend:
    build: ./backend/rni_web
    container_name: rni_backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./backend/rni_web/src:/app
    expose:
      - "8000"
    networks:
      - srni_net

  # ===============================
  # React Frontend (nginx)
  # ===============================
  frontend:
    build:
      context: ./frontend/rni_front
      args:
        VITE_API_URL: https://srni-backend.ngrok.io
    container_name: rni_frontend
    ports:
      - "8085:80"
    depends_on:
      - backend
    networks:
      - srni_net


networks:
  srni_net:
    driver: bridge

volumes:
  srni_pgdata:
