version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_DB: contratistas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - data_stack_net

  mongo:
    image: mongo:7
    container_name: mongo_local
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ./mongo/data:/data/db
    networks:
      - data_stack_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elastic_local
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
    networks:
      - data_stack_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana_local
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - data_stack_net

  minio:
    image: minio/minio:latest
    container_name: minio_local
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Consola Web
    volumes:
      - ./minio/data:/data
    networks:
      - data_stack_net

networks:
  data_stack_net:
    external: true

