services:
  rediapp:
    build: .
    container_name: rediapp_web
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/app
    ports:
      - "8010:8010"
    env_file:
      - .env
    networks:
      - data_stack_net

networks:
  data_stack_net:
    external: true
