services:
  backend:
    build: .
    container_name: rni_backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    networks:
      - data_stack_net


networks:
  data_stack_net:
    external: true
