services:
  backend:
    build: .
    container_name: rni_backend
    ports:
      - "8000:8000"

    # ✅ TU .env real está aquí mismo (backend/rni_web/.env)
    env_file:
      - ./.env

    networks:
      - data_stack_net

networks:
  data_stack_net:
    external: true
